18-rails-forms/cupcakeshop/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # resources :cupcakes
  
  get "/cupcakes", to: 'cupcakes#index'
  get "/cupcakes/new", to: 'cupcakes#new', as: "new_cupcake"
  get "/cupcakes/:id", to: 'cupcakes#show', as: "cupcake"
  post "/cupcakes", to: 'cupcakes#create'
  get "/cupcakes/:id/edit", to: 'cupcakes#edit', as: 'edit_cupcake'
  patch "/cupcakes/:id", to: 'cupcakes#update'
  put "/cupcakes/:id", to: 'cupcakes#update'
  delete "/cupcakes/:id", to: 'cupcakes#destroy'
end

18-rails-forms/cupcakeshop/app/models/cupcake.rb
class Cupcake < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0, only_integer: true }
end

18-rails-forms/cupcakeshop/app/controllers/cupcakes_controller.rb
class CupcakesController < ApplicationController
  before_action :set_cupcake, only: [:show, :edit, :update, :destroy]

  def index
    @cupcakes = Cupcake.all
  end

  def show
  end

  def new
    @cupcake = Cupcake.new
  end

  def create
    @cupcake = Cupcake.create(cupcake_params)
    byebug
    if @cupcake.valid?
      redirect_to @cupcake
    else
      flash[:errors] = @cupcake.errors.full_messages
      redirect_to new_cupcake_path
    end
  end

  def edit
  end

  def update
    @cupcake.update(cupcake_params)
    if @cupcake.valid?
      redirect_to @cupcake
    else
      flash[:errors] = @cupcake.errors.full_messages
      redirect_to edit_cupcake_path(@cupcake)
    end
  end

  def destroy
    @cupcake.destroy
    redirect_to cupcakes_path
  end

  private
  def cupcake_params
    params.require(:cupcake).permit(:name, :price)
  end

  def set_cupcake
    @cupcake = Cupcake.find(params[:id])
  end
end

18-rails-forms/cupcakeshop/app/views/cupcakes/_form.html.erb
<% if flash[:errors] %>
  <ul>
    <% flash[:errors].each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @cupcake do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :price %>
  <%= f.text_field :price %>

  <%= f.submit id: 'submit' %>
<% end %>

18-rails-forms/cupcakeshop/app/views/cupcakes/edit.html.erb
<h1>Edit Cupcake!</h1>

<%= link_to "cancel", cupcake_path(@cupcake) %>

<%= render 'form' %>

<%= form_tag cupcake_path, method: "delete" do %>
  <%= submit_tag "Delete Cupcake" %>
<% end %>

18-rails-forms/cupcakeshop/app/views/cupcakes/index.html.erb
<h1>Get yer cupcakes here!</h1>

<%= link_to "Add Cupcake", new_cupcake_path %>

<ul>
  <% @cupcakes.each do |cupcake| %>
    <li><%= link_to cupcake.name, cupcake %> | £<%= cupcake.price %></li>
  <% end %>
</ul>

18-rails-forms/cupcakeshop/app/views/cupcakes/new.html.erb
<h1>Make a new Cupcake!</h1>

<%= link_to "cancel", cupcakes_path %>

<%= render 'form' %>

18-rails-forms/cupcakeshop/app/views/cupcakes/show.html.erb
<h1><%= @cupcake.name %></h1>

<p>This costs £<%= @cupcake.price %></p>

<%= link_to "All Cupcakes", cupcakes_path %>
<%= link_to "Edit this cupcake", edit_cupcake_path(@cupcake) %>