20-rails-auth/best_kept_secret/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :show, :create, :edit, :update]

  # create the user
  get "/signup", to: 'users#new', as: 'signup'

  # session functionality
  get "/login",     to: 'sessions#new',     as: 'login'
  post "/sessions", to: "sessions#create",  as: 'sessions'
  post "/logout",   to: "sessions#destroy", as: 'logout'

end

20-rails-auth/best_kept_secret/app/models/user.rb
class User < ApplicationRecord
  validates :username, uniqueness: true, presence: true
  has_secure_password
end

20-rails-auth/best_kept_secret/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    if session[:user_id]
      User.find(session[:user_id])
    else
      User.new
    end
  end

  def logged_in?
    !!current_user.id
  end

  def authorized?
    if !logged_in?
      flash[:authorized] = "You aren't logged in"
      redirect_to login_path and return
    end
  end

  def authorized_for(user_id)
    if current_user.admin == true
      true
    elsif current_user.id != user_id.to_i
      flash[:authorized] = "You can't view a page that doesn't belong to you!"
      redirect_to current_user
    end
  end
end

20-rails-auth/best_kept_secret/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user
    else
      flash[:errors] = ["Invalid username or password"]
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

20-rails-auth/best_kept_secret/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      redirect_to @user
    else
      redirect_to new_user_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    if current_user.admin == true
      @users = User.all
    else
      @users = User.all.select{|user| user.admin != true}
    end
  end

  def edit
    authorized_for(params[:id])
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to @user
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :secret)
  end
end

20-rails-auth/best_kept_secret/app/helpers/users_helper.rb
module UsersHelper
end

20-rails-auth/best_kept_secret/app/views/users/edit.html.erb
<h1> Edit your details, <%= @user.username %> </h1>
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.text_field :password %>
  <%= f.label :secret %>
  <%= f.text_field :secret %>
  <%= f.submit %>
<% end %>

20-rails-auth/best_kept_secret/app/views/users/index.html.erb
<h1>What are you about to reveal?</h1>


<% if @users.length > 0 %>
  <ul>
    <% @users.each do |user| %>
      <li class="user"> <%= link_to user.username, user_path(user.id) %> </li>
    <% end %>
  </ul>
<% else %>
  <p> Seem like no one likes to share secrets... </p>
<% end %>

20-rails-auth/best_kept_secret/app/views/users/new.html.erb
<h1> Sign up </h1>
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :secret %>
  <%= f.text_field :secret %>
  <%= f.submit %>
<% end %>

20-rails-auth/best_kept_secret/app/views/users/show.html.erb
<div>
    <h1> <%= @user.username %> </h1>
</div>

<div>
    <p> My secret is: </p>
    <p> <%= @user.secret %></p>
</div>

<% if logged_in? && current_user.id == @user.id || current_user.admin == true %>
    <%= link_to "Edit my secret", edit_user_url %>
<% end %>